spring:
  datasource:
    url: jdbc:h2:mem:ratesdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

demo:
  threads:
    enabled: false

server:
  port: 8080

app:
  executors:
    io:
      # core-size:
      # max-size:
      # queue-capacity:
      thread-name-prefix: "IO-"
    cpu:
      # core-size:
      # max-size:
      # queue-capacity:
      thread-name-prefix: "CPU-"
